config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  resources :books

  resources :rentals, except: [:show] do
    member do
      post :return
    end
  end

  get '/reader_cards/show_reader_card', to: 'reader_cards#show_reader_card', as: 'show_reader_card'
  post '/reader_cards/identify_reader', to: 'reader_cards#identify_reader', as: 'identify_reader'
  get '/reader_cards/forget_reader', to: 'reader_cards#forget_reader', as: 'forget_reader'
  get 'rentals/index_rentals', to: 'rentals#index_rentals', as: 'index_rentals'
end

app/models/reader_card.rb
class ReaderCard < ApplicationRecord
  belongs_to :user
  validates :number, presence: true
  validates :code, presence: true
  validate :user_must_be_a_reader

  private

  def user_must_be_a_reader
    errors.add(:user, "musi być czytelnikiem") unless user.type == "Reader"
  end
end

app/controllers/reader_cards_controller.rb
class ReaderCardsController < ApplicationController
    def show_reader_form
      @book = Book.find(params[:book_id]) if params[:book_id].present?
      @reader_card = ReaderCard.new
    end
  
    def identify_reader
      @reader_card = ReaderCard.find_by(number: params[:number], code: params[:code])
      if @reader_card
        if @reader_card.valid?
          session[:current_reader_id] = @reader_card.user_id
          redirect_to session.delete(:return_to) || root_path, notice: "Czytelnik zidentyfikowany."
        else
            redirect_to show_reader_card_path, alert: "Najpierw zidentyfikuj czytelnika."
        end
      else
        flash[:alert] = "Nieprawidłowy numer lub kod karty."
        redirect_to show_reader_card_path, alert: "Najpierw zidentyfikuj czytelnika."
      end
    end
  
    def forget_reader
      session.delete(:current_reader_id)
      redirect_to root_path, notice: "Czytelnik został zapomniany."
    end
       
  end
  

app/helpers/reader_cards_helper.rb
module ReaderCardsHelper
end

app/views/reader_cards/_form.erb
<%= form_with url: identify_reader_path, method: :post, data: { turbolinks: false }, class: 'mt-3' do |form| %>
  <div class="mb-3">
    <%= form.label :number, "Numer Karty", class: 'form-label' %>
    <%= form.text_field :number, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :code, "Kod Karty", class: 'form-label' %>
    <%= form.password_field :code, class: 'form-control' %>
  </div>

  <%= form.submit "Zidentyfikuj Czytelnika", class: 'btn btn-primary' %>
<% end %>




app/views/reader_cards/show_reader_card.html.erb
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
    <h1>Zweryfikuj czytelnika</h1>
    <%= render 'form' %>

  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>