config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  resources :books

  resources :rentals, except: [:show] do
    member do
      post :return
    end
  end

  get '/reader_cards/show_reader_card', to: 'reader_cards#show_reader_card', as: 'show_reader_card'
  post '/reader_cards/identify_reader', to: 'reader_cards#identify_reader', as: 'identify_reader'
  get '/reader_cards/forget_reader', to: 'reader_cards#forget_reader', as: 'forget_reader'
  get 'rentals/index_rentals', to: 'rentals#index_rentals', as: 'index_rentals'
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :rental_status, presence: true
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :authenticate_user!  # Devise authentication
    before_action :check_librarian, only: [:new, :create, :edit, :update, :destroy]
    before_action :require_reader_identification, only: [:create, :new]
  
     def new
        @rental = Rental.new
        @rental.book_id = params[:book] if params[:book]
      end
  

    def create
      reader = verify_reader(session[:current_reader_id]) 
    if reader

       @rental = Rental.new(rental_params)
       @rental.user_id = reader.id
       @rental.rental_date = Time.current
       @rental.expected_return_date = Date.current + 4.weeks
       @rental.overdue = false
       check_availability

      else
        flash.now[:alert] = "Nieprawidłowy numer lub kod karty."
        render :new
      end
    end

    def index_rentals

      if current_user.type == 'Librarian'
        user_id = session[:current_reader_id]
      elsif current_user.type == 'Reader'
        user_id = current_user.id
      end
      @reader = User.find(user_id) # Zakładając, że identyfikacja czytelnika przechowywana jest w sesji
      @rentals = Rental.where(user_id: @reader.id)
    end

      def return

        @rental = Rental.find_by(id: params[:id])
        @book = Book.find_by(id: @rental.book_id)
      
        if @rental
          @rental.return_date = Time.current
          @rental.rental_status = 'zwrócona'
          @book.update(status: 'dostępna')

          @rental.overdue = check_overdue(@rental)
      
          if @rental.save
            redirect_to index_rentals_path, notice: 'Książka została pomyślnie zwrócona.'
          else
            render :edit, alert: 'Nie udało się zwrócić książki.'
          end
        else
          redirect_to index_rentals_path, alert: 'Nie znaleziono wypożyczenia.'
        end
      end

    private
  
    def rental_params
        params.require(:rental).permit(:book_id)
    end

    def verify_params
        params.require(:rental).permit(:number, :code)
    end
  
    def verify_reader(user_id)
        User.find_by(id: user_id, type: 'Reader')
    end

    def check_librarian
        unless current_user.librarian?
          redirect_to root_path, alert: "Tylko bibliotekarze mogą zarządzać książkami."
        end
    end

    def check_overdue(rental)
      rental.return_date > rental.expected_return_date
    end

    def require_reader_identification
      unless session[:current_reader_id].present?
        session[:return_to] = request.fullpath
        redirect_to show_reader_card_path, alert: "Najpierw zidentyfikuj czytelnika."
      end
    end

    def check_availability
      book = Book.find_by(id: @rental.book_id)
      if book.status == 'dostępna'
        @rental.rental_status = 'wypożyczona'
        book.update(status: 'wypożyczona')

        if @rental.save
          redirect_to book_path(@rental.book_id), notice: "Książka wypożyczona pomyślnie."
        else
          render :new
        end
      else
        redirect_to book_path(@rental.book_id), alert: "Książka nie jest dostępna do wypożyczenia."
      end
    end
  end
  

app/views/rentals/index_rentals.html.erb
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
    <h1>Wypożyczenia Czytelnika: <%= @reader.first_name + " " + @reader.last_name %></h1>

    <div class="list-group">
      <% @rentals.each do |rental| %>
        <div class="list-group-item">
          <div class="row align-items-center">
            <div class="col-md-3">
              <%= image_tag rental.book.image, class: 'book-image2' if rental.book.image.attached? %>
            </div>
            <div class="col-md-6">
              <h3 class="mb-1"><%= link_to rental.book.title, book_path(rental.book) %></h3>
              <p class="mb-1"><strong>Autor:</strong> <%= rental.book.author %></p>
              <p class="mb-1"><strong>Data wypożyczenia:</strong> <%= rental.created_at.to_date %></p>
              <p class="mb-1"><strong>Data zwrotu:</strong> <%= rental.expected_return_date %></p>
              <p class="mb-1"><strong>Data zwrócenia:</strong> <%= rental.return_date || 'Nie zwrócono jeszcze' %></p>
            </div>
            <% if current_user.librarian? && rental.return_date.nil? %>
              <div class="col-md-2 text-md-end">
                <div class="btn-group" role="group" aria-label="Akcje wypożyczenia">
                  <%= link_to 'Zwróć', return_rental_path(rental), method: :post, class: 'btn btn-primary' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>


app/views/rentals/new.html.erb
<!-- app/views/rentals/new.html.erb -->
  <% book = Book.find_by(id: @rental.book_id)  %>
  <% reader = User.find_by(id: session[:current_reader_id])  %>
  <% reader_card = ReaderCard.find_by(user_id: reader.id)  %>
  



<!-- app/views/books/show.html.erb -->
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
<div class="container mt-4">
  <div class="row">
    <h2>Informacje o książce:</h2>
    <div class="col-md-2">
      <% if book.image.attached? %>
        <%= image_tag book.image, class: 'img-fluid', width: '150', height: 'auto' %>
      <% else %>
        <p>Brak zdjęcia.</p>
      <% end %>
    </div>

    <div class="col-md-3">
      <p><strong>Tytuł:</strong> <%= book.title %></p>
      <p><strong>Autor:</strong> <%= book.author %></p>
    </div>


    <h2>Informacje o czytelniku:</h2>

    <div class="col-md-9">
      <p><strong>Imię i nazwisko:</strong> <%= reader.first_name + " " + reader.last_name  %></p>
      <p><strong>Numer karty:</strong> <%= reader_card.number %></p>
    </div>
  </div>

  <%= form_with model: @rental, url: rentals_path, local: true do |form| %>
    <%= form.hidden_field :book_id %>

    <%= form.submit "Wypożycz", class: 'btn btn-primary'%>
  <% end %>

</div>

  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>