config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  resources :books

  resources :rentals, except: [:show] do
    member do
      post :return
    end
  end

  get '/reader_cards/show_reader_card', to: 'reader_cards#show_reader_card', as: 'show_reader_card'
  post '/reader_cards/identify_reader', to: 'reader_cards#identify_reader', as: 'identify_reader'
  get '/reader_cards/forget_reader', to: 'reader_cards#forget_reader', as: 'forget_reader'
  get 'rentals/index_rentals', to: 'rentals#index_rentals', as: 'index_rentals'
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    has_many :rentals
    has_many :readers, through: :rentals

    validates :title, :author, :description, :genre, :release_date, :publisher, :page_number, :translation, :status, :ISBN, presence: true
    
    def self.ransackable_attributes(auth_object = nil)
      %w[title author genre publisher ISBN]
    end
  
    def self.ransackable_associations(auth_object = nil)
      %w[image_attachment image_blob readers rentals]
    end


    def is_available
        status == "dostępna"
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!  # Devise authentication
  before_action :check_librarian, only: [:new, :create, :edit, :update, :destroy]

    def index
      @q = Book.ransack(params[:q])
      @pagy, @books = pagy(@q.result(distinct: true), items: 50)
    end
  
    def show
      @book = Book.find(params[:id])
    end
  
    def new
      @book = Book.new
    end

    def create
        @book = Book.new(book_params)
      
        if @book.save
          redirect_to @book, notice: 'Książka została pomyślnie utworzona.'
        else
          render :new
        end
    end
  
    def edit
      @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
      
        if @book.update(book_params)
          redirect_to @book, notice: 'Książka została pomyślnie zaktualizowana.'
        else
          render :edit
        end
    end
  
    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_url, notice: 'Książka została pomyślnie usunięta.'
    end


    private

    def book_params
        params.require(:book).permit(:image, :title, :author, :description, :genre, :release_date, :publisher, :ISBN, :page_number, :translation, :status)
    end

    def check_librarian
      unless current_user.librarian?
        redirect_to root_path, alert: "Tylko bibliotekarze mogą zarządzać książkami."
      end
    end
end
  

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@book.errors.count, "błąd") %> uniemożliwił zapisanie książki:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :image, class: 'form-label' %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :title, "Tytuł", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :author, "Autor", class: 'form-label' %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Opis", class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :genre, "Gatunek", class: 'form-label' %>
    <%= form.text_field :genre, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :release_date, "Data wydania", class: 'form-label' %>
    <%= form.date_select :release_date, {}, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :publisher, "Wydawnictwo", class: 'form-label' %>
    <%= form.text_field :publisher, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :ISBN, "ISBN", class: 'form-label' %>
    <%= form.text_field :ISBN, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :page_number, "Liczba stron", class: 'form-label' %>
    <%= form.number_field :page_number, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :translation, "Tłumaczenie", class: 'form-label' %>
    <%= form.text_field :translation, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :status, "Status wypożyczenia", class: 'form-label' %>
    <%= form.select :status, ['dostępna', 'wypożyczona', 'niedostępna'], {}, class: 'form-select' %>
  </div>

  <div class="actions">
    <%= form.submit "Zapisz", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<!-- app/views/books/edit.html.erb -->
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
        <h1>Edytuj Książkę</h1>
        <%= render 'form', book: @book %>

        <%= link_to 'Powrót do Listy', books_path %>

  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>

app/views/books/index.html.erb
<!-- app/views/books/index.html.erb -->
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
  
    <h1>Lista Książek</h1>

     <div class="form-row">
      <%= search_form_for @q, class: 'row g-4 mb-4' do |f| %>

        <div class="col-md-4">
          <%= f.label :title_cont, "Wyszukiwanie", class: 'mr-5' %>
          <%= f.search_field :title_cont, class: 'form-control' %>
        </div>
        <div class="col-md-4 d-flex align-items-end">
            <%= f.submit "Szukaj", class: 'btn btn-primary' %>
            <%= link_to 'Wyczyść', books_path, class: 'btn btn-secondary' %>
        </div>
    </div>
    <% end %>

    

    <%== pagy_bootstrap_nav(@pagy) %>
    <div class="list-group">
      <% @books.each do |book| %>
        <div class="list-group-item">
          <div class="row align-items-center">
            <div class="col-md-3">
              <%= image_tag book.image, class: 'book-image' if book.image.attached? %>
            </div>
            <div class="col-md-6">
              <h3 class="mb-1"><%= link_to book.title, book_path(book) %></h3>
              <p class="mb-1"><strong>Autor:</strong> <%= book.author %></p>
              <p class="mb-1"><strong>Gatunek:</strong> <%= book.genre %></p>
              <!-- Dodaj więcej informacji o książce, jeśli potrzebujesz -->
            </div>
            <div class="col-md-3 text-md-end">
              <% if current_user.librarian? %>
                <div class="btn-group" role="group" aria-label="Akcje książki">
                  <%= link_to 'Edytuj', edit_book_path(book), class: "btn btn-warning" %>
                  <%= button_to 'Usuń', book, method: :delete, data: { confirm: "Czy jesteś pewny?" }, class: "btn btn-danger" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <% if current_user.librarian? %>
      <%= link_to 'Dodaj Nową Książkę', new_book_path, class: 'btn btn-primary' %>
    <% end %>

    <div class="col-md-3"> 
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>

app/views/books/new.html.erb
<!-- app/views/books/new.html.erb -->
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
    <h1>Dodaj Nową Książkę</h1>
    <%= render 'form', book: @book %>

    <%= link_to 'Powrót do Listy', books_path %>

  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>

app/views/books/show.html.erb
<!-- app/views/books/show.html.erb -->
<div class="container py-4">
  <div class="p-4 mb-4 bg-light rounded-3">
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3">
      <% if @book.image.attached? %>
        <%= image_tag @book.image, class: 'img-fluid' %>
      <% else %>
        <p>Brak zdjęcia.</p>
      <% end %>
    </div>

    <div class="col-md-9">
      <h1><%= @book.title %></h1>
      <p><strong>Autor:</strong> <%= @book.author %></p>
      <p><strong>Gatunek:</strong> <%= @book.genre %></p>
      <p><strong>Data wydania:</strong> <%= @book.release_date %></p>
      <p><strong>Wydawnictwo:</strong> <%= @book.publisher %></p>
      <p><strong>ISBN:</strong> <%= @book.ISBN %></p>
      <p><strong>Liczba stron:</strong> <%= @book.page_number %></p>
      <p><strong>Tłumaczenie:</strong> <%= @book.translation %></p>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-12">
      <h3>Opis</h3>
      <p><%= @book.description %></p>
      <p><strong>Status wypożyczenia:</strong> <%= @book.status %></p>
    </div>
  </div>

  <!-- Przyciski akcji -->
  <div class="btn-group mt-3" role="group" aria-label="Akcje książki">
    <%= link_to 'Powrót do Listy', books_path, class: 'btn btn-secondary' %>

    <% if current_user.librarian? %>
      <%= link_to 'Edytuj', edit_book_path(@book), class: 'btn btn-warning' %>
      <%= button_to 'Usuń', @book, method: :delete, data: { confirm: 'Czy jesteś pewny?' }, class: 'btn btn-danger' %>

      <% if @book.is_available%>
        <%= link_to 'Wypożycz książkę', new_rental_path(book: @book), class: 'btn btn-primary' %>
      <% else %>
        <%# Link do zwrotu książki %>
      <% end %>
    <% end %>
  </div>
</div>

  </div>
</div>

<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy; Sonia Leszkiewicz 2023</p>
</footer>