config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  resources :books

  resources :rentals, except: [:show] do
    member do
      post :return
    end
  end

  get '/reader_cards/show_reader_card', to: 'reader_cards#show_reader_card', as: 'show_reader_card'
  post '/reader_cards/identify_reader', to: 'reader_cards#identify_reader', as: 'identify_reader'
  get '/reader_cards/forget_reader', to: 'reader_cards#forget_reader', as: 'forget_reader'
  get 'rentals/index_rentals', to: 'rentals#index_rentals', as: 'index_rentals'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-blue">
      <div class="container-fluid">
        <div class="d-flex justify-content-between w-100">
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? && current_user.type == 'Reader' %>
              <li class="nav-item">
                <%= link_to 'Wypożyczenia', index_rentals_path, class: 'btn btn-accent2' %>
              </li>
            <% end %>
            <% if user_signed_in? && current_user.type == 'Librarian' %>
                  <% if current_user.type == 'Librarian' && session[:current_reader_id].present? %>
                    <li><%= link_to 'Wypożyczenia Czytelnika', index_rentals_path, class: 'btn btn-accent2' %></li>
                    <li><%= link_to 'Zapomnij czytelnika', forget_reader_path, class: 'btn btn-accent2' %></li>
                    <% else %>
                    <li class="nav-item">
                     <%= link_to 'Zweryfikuj czytelnika', show_reader_card_path, class: 'btn btn-accent2' %>
                    </li>
                  <% end %>
            <% end %>
          </ul>
          <a class="navbar-brand navbar-brand-custom" href="<%= root_path %>">Biblioteka</a>
          <ul class="navbar-nav ms-auto">
            <%= button_to 'Powrót', 'javascript:history.back()', method: :get, class: 'btn btn-secondary' %>
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle btn btn-accent2" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Moje konto
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><%= link_to 'Edytuj profil', edit_user_registration_path, class: 'dropdown-item' %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to 'Wyloguj', destroy_user_session_path, class: 'dropdown-item' %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Zaloguj', new_user_session_path, class: 'btn btn-accent2' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>